[tool.poetry]
<<<<<<< HEAD
name = "onlyfans"
version = "0.1.0"
description = ""
authors = ["john"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
urllib3 = "^2.0.6"
win32-setctime = "^1.1.0"
python-socks = {extras = ["asyncio"], version = "^2.4.3"}
psutil = "^5.9.6"
python-dateutil = "^2.8.2"
lxml = "^4.9.3"
mergedeep = "^1.3.4"
jsonpickle = "^3.0.2"
ujson = "^5.8.0"
sqlalchemy = "1.4.20"
alembic = "^1.12.0"
tqdm = ">=4.62.0"
selenium = "^4.14.0"
selenium-wire = "2.1.2"
user-agent = "^0.1.10"
aiohttp = "^3.8.6"
aiohttp-socks = "^0.8.4"
=======
name = "ultima-scraper"
version = "8.0.0"
description = ""
authors = [
    "DIGITALCRIMINALS <89371864+digitalcriminals@users.noreply.github.com>",
]
license = "GPL-3.0"
readme = "README.md"
packages = [{ include = "ultima_scraper" }]
include = ["ultima_scraper/py.typed"]

[tool.poetry.dependencies]
python = "^3.10 <3.12"
requests = "^2.26.0"
ultima-scraper-api = "1.1.4"
ultima-scraper-collection = "1.1.3"
ultima-scraper-renamer = "1.1.1"
[tool.poetry.dev-dependencies]
pyinstaller = { version = "^5.0.1", markers = "sys_platform == 'win32'" }
requests-html = "^0.10.0"
black = "^22.6.0"
>>>>>>> 3236bbaeb522a9325159481439c23fcd7c5649b6


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
